replicaCount: 1

image:
  repository: saurabhvirkar/skfabricator-backend
  tag: "stage-latest"

backendSecret:
  existingSecret: "backend-api-secrets"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: api.stage.skfabricator.local
      paths:
        - path: /
          pathType: Prefix
    - host: stage-api.skfabricator.com
      paths:
        - path: /
          pathType: Prefix

env:
  ASPNETCORE_ENVIRONMENT: "Stage"
  ALLOWED_ORIGINS: "http://stage.skfabricator.local,https://stage.skfabricator.com"

configMap:
  data:
    Logging__LogLevel__Default: "Information"
    Logging__LogLevel__Microsoft.AspNetCore: "Warning"

