replicaCount: 1

image:
  repository: saurabhvirkar/skfabricator-frontend
  tag: "stage-latest"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: stage.skfabricator.local
      paths:
        - path: /
          pathType: Prefix
    - host: stage.skfabricator.com
      paths:
        - path: /
          pathType: Prefix

configMap:
  data:
    API_URL: "http://api.stage.skfabricator.local"
    ENVIRONMENT: "stage"

