replicaCount: 2

image:
  tag: "staging"

resources:
  limits:
    cpu: 400m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  ASPNETCORE_ENVIRONMENT: "Staging"
  ALLOWED_ORIGINS: "https://staging.skfabricator.com"
