replicaCount: 2

image:
  tag: "staging"

resources:
  limits:
    cpu: 200m
    memory: 192Mi
  requests:
    cpu: 50m
    memory: 64Mi

configMap:
  data:
    API_URL: "https://api-staging.skfabricator.com"
    ENVIRONMENT: "staging"
