apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
  annotations:
    policies.kyverno.io/title: Require Resource Limits
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    description: >-
      Containers must define CPU and memory requests and limits for cluster resource governance.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: validate-resources
      match:
        any:
          - resources:
              namespaces:
                - sk-fabricator-dev
                - sk-fabricator-stage
                - sk-fabricator-prod
              kinds:
                - Pod
      validate:
        message: "CPU and Memory requests and limits must be specified."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"
                    memory: "?*"
