apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres-db
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
      name: postgres
  selector:
    app: postgres-db
