replicaCount: 3

image:
  repository: ghcr.io/saurabhvirkar/skfabricator-backend
  tag: "1.0.0"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/limit-rps: "20"
  hosts:
    - host: api.skfabricator.com
      paths:
        - path: /
          pathType: Prefix

env:
  ASPNETCORE_ENVIRONMENT: "Production"
  ALLOWED_ORIGINS: "https://skfabricator.com"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi

configMap:
  data:
    Logging__LogLevel__Default: "Warning"
    Logging__LogLevel__Microsoft.AspNetCore: "Warning"
