replicaCount: 1

image:
  repository: saurabhvirkar/skfabricator-backend
  tag: "1.0.0"

backendSecret:
  existingSecret: "backend-api-secrets"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: api.prod.skfabricator.local
      paths:
        - path: /
          pathType: Prefix
    - host: api.skfabricator.com
      paths:
        - path: /
          pathType: Prefix

env:
  ASPNETCORE_ENVIRONMENT: "Production"
  ALLOWED_ORIGINS: "http://prod.skfabricator.local,https://skfabricator.com"

configMap:
  data:
    Logging__LogLevel__Default: "Warning"
    Logging__LogLevel__Microsoft.AspNetCore: "Error"

