replicaCount: 3

image:
  repository: ghcr.io/saurabhvirkar/skfabricator-backend
  tag: "1.0.0"

backendSecret:
  existingSecret: "backend-api-secrets"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.skfabricator.com
      paths:
        - path: /
          pathType: Prefix

env:
  ASPNETCORE_ENVIRONMENT: "Production"
  ALLOWED_ORIGINS: "https://skfabricator.com"

configMap:
  data:
    Logging__LogLevel__Default: "Warning"
    Logging__LogLevel__Microsoft.AspNetCore: "Error"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
