replicaCount: 3

image:
  repository: ghcr.io/saurabhvirkar/skfabricator-frontend
  tag: "1.0.0"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "50"
  hosts:
    - host: skfabricator.com
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

configMap:
  data:
    API_URL: "https://api.skfabricator.com"
    ENVIRONMENT: "production"
