{{- if not .Values.backendSecret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.backendSecret.connectionString | quote }}
  JwtSettings__Secret: {{ .Values.backendSecret.jwtSecret | quote }}
  CloudinarySettings__CloudName: {{ .Values.backendSecret.cloudinaryCloudName | quote }}
  CloudinarySettings__ApiKey: {{ .Values.backendSecret.cloudinaryApiKey | quote }}
  CloudinarySettings__ApiSecret: {{ .Values.backendSecret.cloudinaryApiSecret | quote }}
  SmtpSettings__Password: {{ .Values.backendSecret.smtpPassword | quote }}
{{- end }}
