apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skfabricator-postgres-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_GITHUB_USERNAME/sk-gitops-manifests.git'
    targetRevision: HEAD
    path: helm/postgres
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
