apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skfabricator-frontend-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: skfabricator-prod
  source:
    repoURL: 'https://github.com/saurabhvirkar/sk-fabricator-gitops.git'
    targetRevision: main
    path: charts/frontend
    helm:
      valueFiles:
        - '../../environments/prod/frontend-values.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sk-fabricator-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
