apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skfabricator-postgres-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: skfabricator-dev
  source:
    repoURL: 'https://github.com/saurabhvirkar/sk-fabricator-gitops.git'
    targetRevision: develop
    path: charts/postgres
    helm:
      valueFiles:
        - '../../environments/dev/postgres-values.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sk-fabricator-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
