replicaCount: 1

image:
  repository: ghcr.io/saurabhvirkar/skfabricator-backend
  tag: "dev-latest"

backendSecret:
  existingSecret: "backend-api-secrets"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: api.skfabricator.local
      paths:
        - path: /
          pathType: Prefix

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  ALLOWED_ORIGINS: "http://localhost,http://skfabricator.local"

configMap:
  data:
    Logging__LogLevel__Default: "Debug"
    Logging__LogLevel__Microsoft.AspNetCore: "Information"
