replicaCount: 1

image:
  repository: skfabricator-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  API_URL: "http://api.skfabricator.local"
