replicaCount: 1

image:
  repository: saurabhvirkar/skfabricator-frontend
  tag: "dev-latest"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: skfabricator.local
      paths:
        - path: /
          pathType: Prefix

configMap:
  data:
    API_URL: "http://api.skfabricator.local"
    ENVIRONMENT: "development"
