replicaCount: 1

image:
  tag: "latest"

resources:
  limits:
    cpu: 150m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 32Mi

configMap:
  data:
    API_URL: "http://api.skfabricator.local"
    ENVIRONMENT: "development"
